# Generated by Django 5.0.2 on 2024-02-17 10:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('dp', models.ImageField(default='default.jpg', upload_to='dp/')),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('designer', 'designer'), ('parent', 'parent')], default='student', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('natural science', 'natural science'), ('mathematics', 'mathematics'), ('english language and literature', 'English Language & Literature'), ('computer science', 'Computer Science')], max_length=32)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('affiliation_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('contract_duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Anouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('anounce', models.ImageField(upload_to='anouncements/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('designer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('subjects', models.ManyToManyField(related_name='students', to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Gaurdianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='accounts.profile')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departement')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice', to='accounts.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_sent', to='accounts.teacher')),
            ],
        ),
    ]
